

services:
 # --- SERVICIO : ALMACENAMIENTO (MinIO) ---
  minio:
    image: minio/minio
    container_name: ligamx-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # API 
      - "9001:9001" # Consola Web 
    volumes:
      - minio-data:/data

  ligamx-service:
    image: hilariotetsu/api-ligamx:latest
    container_name: ligamx-service
    ports:
      - "8080:8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - minio
        


volumes:
  minio-data: