spring.datasource.url=jdbc:sqlserver://localhost:1435;databaseName=LigaMX;encrypt=true;trustServerCertificate=true
spring.datasource.username=hilario
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

app.s3.endpoint=http://localhost:9000
app.s3.accessKey=minioadmin
app.s3.secretKey=minioadmin
app.s3.bucket=ligamxdata
app.s3.region=us-east-1
app.s3.maxSizeBytes=3145728