server.server.context-path:/ligaMXFDF

spring.application.name=liga-mx


spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



app.jwt.secretkey = panTieso@1988kamurocho?jojoPart7Ineedit;vectorTransversalDirigidoAlEspacio:ArribaLasUmas
app.jwt.expiration-minutes=60