BEGIN TRAN TRAN_1 
	BEGIN TRY
	
	
	BULK INSERT NACIONALIDADES
	FROM 'C:\temp\CAT_NACIONALIDADES.csv'
	
	WITH (
		FIELDTERMINATOR = ',',
		ROWTERMINATOR = '\n',
		FIRSTROW = 2
	);
	
	
	BULK INSERT ESTADOS
	FROM 'C:\temp\ENTIDAD_FEDERATIVA_201602.csv'
	
	WITH (
		FIELDTERMINATOR = ',',
		ROWTERMINATOR = '\n',
		FIRSTROW = 2
	);
	
	BULK INSERT CIUDADES
	FROM 'C:\temp\MUNICIPIOS_202510.csv'
	WITH (
		FIELDTERMINATOR = ',',
		ROWTERMINATOR = '\n',
		FIRSTROW = 2
	);
	
	
	COMMIT TRAN TRAN_1; 
	PRINT 'PROCESO EJECUTADO CORRECTAMENTE'; 
	END TRY 
BEGIN CATCH 
SELECT 'LINEA ERROR - '+ CAST(ERROR_LINE() AS VARCHAR(5)) + ':' + ERROR_MESSAGE(); 
ROLLBACK TRAN TRAN_1; PRINT 'OCURRIO UN ERROR EN EL PROCESO'; 
END CATCH		