BEGIN TRAN TRAN_1 
	BEGIN TRY
	
		IF OBJECT_ID('dbo.TIPOS_PARTIDOS') IS NOT NULL
		DROP TABLE dbo.TIPOS_PARTIDOS
		
		CREATE TABLE TIPOS_PARTIDOS
		(
			ID_TIPO	TINYINT NOT NULL,
			DESCRIPCION_TIPO NVARCHAR(75) NOT NULL,
			CONSTRAINT PK_TIPO_PARTIDO PRIMARY KEY(ID_TIPO)
		)
		
		IF OBJECT_ID('dbo.TIPO_TRASPASOS') IS NOT NULL
		DROP TABLE dbo.TIPO_TRASPASOS
		
		CREATE TABLE TIPOS_TRASPASOS
		(
			ID_TIPO	TINYINT NOT NULL,
			DESCRIPCION_TIPO NVARCHAR(75) NOT NULL,
			CONSTRAINT PK_TIPO_TRASPASOS PRIMARY KEY(ID_TIPO)
		)
	
		IF OBJECT_ID ('dbo.STATUS') IS NOT NULL 
		DROP TABLE dbo.STATUS
		
		CREATE TABLE STATUS
		(
			ID_STATUS	TINYINT NOT NULL,
			DESCRIPCION_STATUS NVARCHAR(100) NOT NULL,
			CONSTRAINT PK_STATUS PRIMARY KEY(ID_STATUS)
		)
		
		
		IF OBJECT_ID ('dbo.NACIONALIDADES') IS NOT NULL 
		DROP TABLE dbo.NACIONALIDADES
		
		CREATE TABLE NACIONALIDADES
		(
			ID_NACIONALIDAD	SMALLINT NOT NULL,
			NOMBRE_NACIONALIDAD NVARCHAR(150) NOT NULL,
			CONSTRAINT PK_NACIONALIDAD PRIMARY KEY(ID_NACIONALIDAD)
		)
		
		IF OBJECT_ID ('dbo.ESTADOS') IS NOT NULL 
		DROP TABLE dbo.ESTADOS
		
		CREATE TABLE ESTADOS
		(
			ID_ESTADO	TINYINT NOT NULL,
			NOMBRE_ESTADO NVARCHAR(150) NOT NULL,
			CONSTRAINT PK_ESTADO PRIMARY KEY(ID_ESTADO)
		)
		
		IF OBJECT_ID ('dbo.POSICIONES') IS NOT NULL 
		DROP TABLE dbo.POSICIONES
		
		CREATE TABLE POSICIONES
		(
			ID_POSICION	TINYINT NOT NULL,
			DESCRIPCION_POSICION NVARCHAR(50) NOT NULL,
			CONSTRAINT PK_POSICION PRIMARY KEY(ID_POSICION)
		)
		
		IF OBJECT_ID ('dbo.CATEGORIAS') IS NOT NULL 
		DROP TABLE dbo.CATEGORIAS
		
		CREATE TABLE CATEGORIAS
		(
			ID_CATEGORIA	TINYINT NOT NULL,
			DESCRIPCION_CATEGORIA NVARCHAR(50) NOT NULL,
			CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
		)
		
		IF OBJECT_ID ('dbo.TIPOS_ACONTECIMIENTOS') IS NOT NULL 
		DROP TABLE dbo.TIPOS_ACONTECIMIENTOS
		
		CREATE TABLE TIPOS_ACONTECIMIENTOS
		(
			ID_TIPO	TINYINT NOT NULL,
			DESCRIPCION_TIPO NVARCHAR(50) NOT NULL,
			CONSTRAINT PK_TIPO_ACONTECIMIENTO PRIMARY KEY(ID_TIPO)
		)
		
		IF OBJECT_ID ('dbo.CIUDADES') IS NOT NULL 
		DROP TABLE dbo.CIUDADES
		
		CREATE TABLE CIUDADES
		(
			ID_CIUDAD	SMALLINT NOT NULL,
			NOMBRE_CIUDAD NVARCHAR(200) NOT NULL,
			ID_ESTADO TINYINT NOT NULL,
			CONSTRAINT PK_CIUDAD PRIMARY KEY(ID_CIUDAD),
			CONSTRAINT FK_ESTADO_CIUDAD FOREIGN KEY(ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.PERSONAS') IS NOT NULL 
		DROP TABLE dbo.PERSONAS

		CREATE TABLE PERSONAS
		(
			ID_PERSONA		UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
			NOMBRE	NVARCHAR(255) NOT NULL,
			FECHA_NACIMIENTO	DATE NOT NULL,
			LUGAR_NACIMIENTO	NVARCHAR(255) NOT NULL,
			ESTATURA NUMERIC(3,2) NOT NULL,
			PESO NUMERIC(4,1) NOT NULL,
			ID_STATUS TINYINT NOT NULL,
			ID_NACIONALIDAD SMALLINT NOT NULL,
			CONSTRAINT PK_PERSONA PRIMARY KEY(ID_PERSONA),
			CONSTRAINT FK_STATUS_PERSONAS FOREIGN KEY(ID_STATUS) REFERENCES STATUS(ID_STATUS) ON DELETE NO ACTION,
			CONSTRAINT FK_NACIONALIDAD_PERSONAS FOREIGN KEY(ID_NACIONALIDAD) REFERENCES NACIONALIDADES(ID_NACIONALIDAD) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.DIRECTORES_TECNICOS') IS NOT NULL 
		DROP TABLE dbo.DIRECTORES_TECNICOS
		
		CREATE TABLE DIRECTORES_TECNICOS
		(
			NUI_DT BIGINT IDENTITY(1,1) NOT NULL,
			TARJETAS_AMARILLAS TINYINT NULL,
			TARJETAS_ROJAS TINYINT NULL,
			ID_PERSONA UNIQUEIDENTIFIER NOT NULL,
			CONSTRAINT PK_DT PRIMARY KEY(NUI_DT),
			CONSTRAINT FK_PERSONA_DT FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.ARBITROS') IS NOT NULL 
		DROP TABLE dbo.ARBITROS
		
		CREATE TABLE ARBITROS
		(
			NUI_ARBITRO BIGINT IDENTITY(1,1) NOT NULL,
			ID_PERSONA UNIQUEIDENTIFIER NOT NULL,
			FECHA_INCORPORACION DATE NOT NULL,
			ID_CATEGORIA TINYINT NOT NULL,
			CONSTRAINT PK_ARBITRO PRIMARY KEY(NUI_ARBITRO),
			CONSTRAINT FK_PERSONA_ARBITRO FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE NO ACTION,
			CONSTRAINT FK_CATEGORIA_ARBITRO FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA) ON DELETE NO ACTION
			
		)

		IF OBJECT_ID('dbo.ESTADIOS') IS NOT NULL
		DROP TABLE dbo.ESTADIOS
		
		CREATE TABLE ESTADIOS
		(
			ID_ESTADIO SMALLINT IDENTITY(1,1) NOT NULL,
			NOMBRE_ESTADIO NVARCHAR(250) NOT NULL,
			DIRECCION NVARCHAR(300) NOT NULL,
			CAPACIDAD INT NOT NULL,
			ID_ESTADO TINYINT NOT NULL,
			ID_CIUDAD SMALLINT NOT NULL,
			CONSTRAINT PK_ESTADIO PRIMARY KEY(ID_ESTADIO),
			CONSTRAINT FK_ESTADO_ESTADIO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO) ON DELETE NO ACTION,
			CONSTRAINT FK_CIUDAD_ESTADIO FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID('dbo.CLUBES') IS NOT NULL
		DROP TABLE dbo.CLUBES
		
		CREATE TABLE CLUBES
		(
			ID_CLUB TINYINT IDENTITY(1,1) NOT NULL,
			NOMBRE_CLUB VARCHAR(150) NOT NULL,
			FECHA_FUNDACION DATE NOT NULL,
			PROPIETARIO NVARCHAR(255) NOT NULL,
			ID_ESTADO TINYINT NOT NULL,
			ID_CIUDAD SMALLINT NOT NULL,
			ID_DT BIGINT NOT NULL,
			ID_ESTADIO SMALLINT NOT NULL,
			CONSTRAINT PK_CLUB PRIMARY KEY(ID_CLUB),
			CONSTRAINT UQ_CLUB_DT UNIQUE(ID_DT),
			CONSTRAINT FK_ESTADO_CLUB FOREIGN KEY(ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO) ON DELETE NO ACTION,
			CONSTRAINT FK_CIUDAD_CLUB FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD) ON DELETE NO ACTION,
			CONSTRAINT FK_DT_CLUB FOREIGN KEY(ID_DT) REFERENCES DIRECTORES_TECNICOS(NUI_DT) ON DELETE NO ACTION,
			CONSTRAINT FK_ESTADIO_CLUB FOREIGN KEY(ID_ESTADIO) REFERENCES ESTADIOS(ID_ESTADIO) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.JUGADORES') IS NOT NULL 
		DROP TABLE dbo.JUGADORES
		
		CREATE TABLE JUGADORES
		(
			NUI_JUGADOR BIGINT IDENTITY(1,1) NOT NULL,
			TARJETAS_AMARILLAS TINYINT NULL,
			TARJETAS_ROJAS TINYINT NULL,
			DORSAL TINYINT NOT NULL,
			ID_PERSONA UNIQUEIDENTIFIER NOT NULL,
			ID_POSICION TINYINT NOT NULL,
			ID_CLUB TINYINT NOT NULL,
			CONSTRAINT PK_JUGADOR PRIMARY KEY(NUI_JUGADOR),
			CONSTRAINT FK_PERSONA_JUGADOR FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE NO ACTION,
			CONSTRAINT FK_POSICION_JUGADOR FOREIGN KEY(ID_POSICION) REFERENCES POSICIONES(ID_POSICION) ON DELETE NO ACTION,
			CONSTRAINT FK_CLUB_JUGADOR FOREIGN KEY(ID_CLUB) REFERENCES CLUBES(ID_CLUB) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.TRASPASOS') IS NOT NULL 
		DROP TABLE dbo.TRASPASOS
		
		CREATE TABLE TRASPASOS
		(
			ID_TRASPASO UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
			NUI_JUGADOR BIGINT NOT NULL,
			ID_CLUBORIGEN TINYINT  NULL,
			ID_CLUBDESTINO TINYINT NULL,
			VALOR	NUMERIC(15,4) NULL,
			FECHA_TRASPASO	DATETIME NULL,
			FECHA_FIN DATETIME NULL,
			ID_TIPO TINYINT NOT NULL,
			CONSTRAINT PK_TRASPASOS PRIMARY KEY(ID_TRASPASO),
			CONSTRAINT FK_TRASPASOS_JUGADOR FOREIGN KEY(NUI_JUGADOR) REFERENCES JUGADORES(NUI_JUGADOR) ON DELETE NO ACTION, 
			CONSTRAINT FK_TRASPASOS_TIPOS FOREIGN KEY(ID_TIPO) REFERENCES TIPOS_TRASPASOS(ID_TIPO) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.TORNEOS') IS NOT NULL 
		DROP TABLE dbo.TORNEOS
		
		CREATE TABLE TORNEOS
		(
		ID_TORNEO BIGINT NOT NULL,
		NOMBRE_TORNEO NVARCHAR(100) NULL,
		FECHA_INICIO DATE NOT NULL,
		FECHA_FIN DATE NOT NULL,
		STATUS SMALLINT NULL,
		CONSTRAINT PK_TORNEO PRIMARY KEY(ID_TORNEO)
		)

		IF OBJECT_ID ('dbo.PARTIDOS') IS NOT NULL 
		DROP TABLE dbo.PARTIDOS
		
		CREATE TABLE PARTIDOS
		(
			ID_PARTIDO  UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
			ID_LOCAL TINYINT NOT NULL,
			ID_VISITANTE TINYINT NOT NULL,
			ID_ESTADIO SMALLINT NOT NULL,
			GOLES_LOCAL TINYINT NULL,
			GOLES_VISITANTE TINYINT NULL,
			ID_ARBITRO_CENTRAL BIGINT NOT NULL,
			ID_CUARTO_ARBITRO BIGINT NULL,
			ID_ARBITRO_ASISTENTE1 BIGINT NULL,
			ID_ARBITRO_ASISTENTE2 BIGINT NULL,
			FECHA DATETIME NOT NULL,
			ID_STATUS TINYINT NOT NULL,
			ID_TORNEO BIGINT NOT NULL,
			ID_TIPO TINYINT NULL,
			CONSTRAINT PK_PARTIDO PRIMARY KEY(ID_PARTIDO),
			CONSTRAINT FK_LOCAL FOREIGN KEY(ID_LOCAL) REFERENCES CLUBES(ID_CLUB) ON DELETE NO ACTION,
			CONSTRAINT FK_VISITANTE FOREIGN KEY(ID_VISITANTE) REFERENCES CLUBES(ID_CLUB) ON DELETE NO ACTION,
			CONSTRAINT FK_ESTADIO_PARTIDO FOREIGN KEY(ID_ESTADIO) REFERENCES ESTADIOS(ID_ESTADIO) ON DELETE NO ACTION,
			CONSTRAINT FK_ARBITRO_CENTRAL FOREIGN KEY(ID_ARBITRO_CENTRAL) REFERENCES ARBITROS(NUI_ARBITRO) ON DELETE NO ACTION,
			CONSTRAINT FK_CUARTO_ARBITRO FOREIGN KEY(ID_CUARTO_ARBITRO) REFERENCES ARBITROS(NUI_ARBITRO) ON DELETE NO ACTION,
			CONSTRAINT FK_ARBITRO_ASISTENTE1 FOREIGN KEY(ID_ARBITRO_ASISTENTE1) REFERENCES ARBITROS(NUI_ARBITRO) ON DELETE NO ACTION,
			CONSTRAINT FK_ARBITRO_ASISTENTE2 FOREIGN KEY(ID_ARBITRO_ASISTENTE2) REFERENCES ARBITROS(NUI_ARBITRO) ON DELETE NO ACTION,
			CONSTRAINT FK_STATUS_PARTIDO FOREIGN KEY(ID_STATUS) REFERENCES STATUS(ID_STATUS) ON DELETE NO ACTION,
			CONSTRAINT FK_PARTIDO_TORNEO FOREIGN KEY(ID_TORNEO) REFERENCES TORNEOS(ID_TORNEO) ON DELETE NO ACTION
		)
		
		IF OBJECT_ID ('dbo.ACONTECIMIENTOS') IS NOT NULL 
		DROP TABLE dbo.ACONTECIMIENTOS
		
		CREATE TABLE ACONTECIMIENTOS
		(
			ID_ACONTECIMEINTO UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
			ID_TIPO TINYINT NOT NULL,
			MINUTO NVARCHAR(10) NOT NULL,
			ID_JUGADOR_PRIMARIO BIGINT NOT NULL,
			ID_JUGADOR_SECUNDARIO BIGINT NULL,
			ID_PARTIDO UNIQUEIDENTIFIER NOT NULL,
			CONSTRAINT PK_ACONTECIMIENTO PRIMARY KEY(ID_ACONTECIMEINTO),
			CONSTRAINT FK_TIPO_ACONTECIMIENTO FOREIGN KEY(ID_TIPO) REFERENCES TIPOS_ACONTECIMIENTOS(ID_TIPO) ON DELETE NO ACTION,
			CONSTRAINT FK_JUGADOR_PRIMARIO FOREIGN KEY(ID_JUGADOR_PRIMARIO) REFERENCES JUGADORES(NUI_JUGADOR) ON DELETE NO ACTION,
			CONSTRAINT FK_JUGADOR_SECUNDARIO FOREIGN KEY(ID_JUGADOR_SECUNDARIO) REFERENCES JUGADORES(NUI_JUGADOR) ON DELETE NO ACTION,
			CONSTRAINT FK_PARTIDO_ACONTECIMIENTO FOREIGN KEY(ID_PARTIDO) REFERENCES PARTIDOS(ID_PARTIDO) ON DELETE NO ACTION
		)
		
	COMMIT TRAN TRAN_1; 
	PRINT 'PROCESO EJECUTADO CORRECTAMENTE'; 
	END TRY 
BEGIN CATCH 
SELECT 'LINEA ERROR - '+ CAST(ERROR_LINE() AS VARCHAR(5)) + ':' + ERROR_MESSAGE(); 
ROLLBACK TRAN TRAN_1; PRINT 'OCURRIO UN ERROR EN EL PROCESO'; 
END CATCH		