SELECT
	P.NOMBRE,
	J.DORSAL,
	C.NOMBRE_CLUB, 
	N.NOMBRE_NACIONALIDAD, 
	COUNT(*) AS GOLES
FROM
	JUGADORES AS J
INNER JOIN ACONTECIMIENTOS AS A ON J.NUI_JUGADOR = A.ID_JUGADOR_PRIMARIO
AND A.ID_TIPO = 1
LEFT JOIN CLUBES AS C ON J.ID_CLUB = C.ID_CLUB
INNER JOIN PERSONAS AS P ON J.ID_PERSONA = P.ID_PERSONA
INNER JOIN NACIONALIDADES AS N ON P.ID_NACIONALIDAD = N.ID_NACIONALIDAD 
INNER JOIN PARTIDOS AS PA ON A.ID_PARTIDO  = PA.ID_PARTIDO
INNER JOIN TORNEOS AS T ON PA.ID_TORNEO = T.ID_TORNEO 
AND T.ID_TORNEO = 7
GROUP BY P.NOMBRE, J.DORSAL, C.NOMBRE_CLUB, N.NOMBRE_NACIONALIDAD   
ORDER BY GOLES DESC
