SELECT 
	C.NOMBRE_CLUB AS CLUB,
	SUM(CASE
		WHEN P.ID_STATUS = 5
		THEN 1
	END
	) AS TPJ,
	SUM(CASE
        WHEN P.ID_STATUS = 5 AND (
            (P.ID_LOCAL = C.ID_CLUB AND P.GOLES_LOCAL > P.GOLES_VISITANTE)
            OR
            (P.ID_VISITANTE = C.ID_CLUB AND P.GOLES_VISITANTE > P.GOLES_LOCAL)
        ) THEN 3
        WHEN P.ID_STATUS = 5 AND P.GOLES_LOCAL = P.GOLES_VISITANTE 
        THEN 1
        ELSE 0
	END
	) AS PUNTOS,
	ROUND(
	SUM(CASE
        WHEN P.ID_STATUS = 5 AND (
            (P.ID_LOCAL = C.ID_CLUB AND P.GOLES_LOCAL > P.GOLES_VISITANTE)
            OR
            (P.ID_VISITANTE = C.ID_CLUB AND P.GOLES_VISITANTE > P.GOLES_LOCAL)
        ) THEN 3
        WHEN P.ID_STATUS = 5 AND P.GOLES_LOCAL = P.GOLES_VISITANTE 
        THEN 1
        ELSE 0
	END
	) * 1.0  /
	NULLIF(SUM(CASE
		WHEN P.ID_STATUS = 5
		THEN 1
	END), 0), 4) AS COCIENTE
FROM
	CLUBES AS C
INNER JOIN PARTIDOS AS P ON
	C.ID_CLUB IN (P.ID_LOCAL, P.ID_VISITANTE)
INNER JOIN TORNEOS AS T ON
	P.ID_TORNEO = T.ID_TORNEO
WHERE
	T.ID_TORNEO IN(
SELECT TOP 6 T.ID_TORNEO 
FROM TORNEOS 
ORDER BY TORNEOS.FECHA_FIN DESC)
GROUP BY
	C.NOMBRE_CLUB
ORDER BY
	COCIENTE DESC

	
--select COUNT(*) from PARTIDOS p 
--WHERE p.ID_TORNEO = 1
