SELECT
    C.NOMBRE_CLUB AS CLUB,   
    SUM(CASE 
        WHEN P.ID_STATUS = 5 THEN 1
        ELSE 0
    END) AS PARTIDOS_JUGADOS,
    SUM(CASE 
        WHEN P.ID_STATUS = 5
        AND (
            (P.ID_LOCAL = C.ID_CLUB AND P.GOLES_LOCAL > P.GOLES_VISITANTE)
            OR
            (P.ID_VISITANTE = C.ID_CLUB AND P.GOLES_VISITANTE > P.GOLES_LOCAL)
        )
        THEN 1 ELSE 0
    END) AS PARTIDOS_GANADOS,
    SUM(CASE
        WHEN P.ID_STATUS = 5
        AND P.GOLES_LOCAL = P.GOLES_VISITANTE
        THEN 1 ELSE 0
    END) AS PARTIDOS_EMPATADOS,
    SUM(CASE 
        WHEN P.ID_STATUS = 5
        AND (
            (P.ID_LOCAL = C.ID_CLUB AND P.GOLES_LOCAL < P.GOLES_VISITANTE)
            OR
            (P.ID_VISITANTE = C.ID_CLUB AND P.GOLES_VISITANTE < P.GOLES_LOCAL)
        )
        THEN 1 ELSE 0
    END) AS PARTIDOS_PERDIDOS,
    SUM(CASE
        WHEN P.ID_LOCAL = C.ID_CLUB THEN ISNULL(P.GOLES_LOCAL,0)
        WHEN P.ID_VISITANTE = C.ID_CLUB THEN ISNULL(P.GOLES_VISITANTE,0)
        ELSE 0
    END) AS GOLES_A_FAVOR,
    SUM(CASE
        WHEN P.ID_LOCAL = C.ID_CLUB THEN ISNULL(P.GOLES_VISITANTE,0)
        WHEN P.ID_VISITANTE = C.ID_CLUB THEN ISNULL(P.GOLES_LOCAL,0)
        ELSE 0
    END) AS GOLES_EN_CONTRA, 
    SUM(CASE
        WHEN P.ID_LOCAL = C.ID_CLUB THEN CAST(ISNULL(P.GOLES_LOCAL,0)AS INT) - CAST(ISNULL(P.GOLES_VISITANTE,0)AS INT)
        WHEN P.ID_VISITANTE = C.ID_CLUB THEN CAST(ISNULL(P.GOLES_VISITANTE,0)AS INT) - CAST(ISNULL(P.GOLES_LOCAL,0)AS INT)
        ELSE 0
    END) AS DIFERENCIA_GOLES,
    SUM(CASE
        WHEN P.ID_STATUS = 5 AND (
            (P.ID_LOCAL = C.ID_CLUB AND P.GOLES_LOCAL > P.GOLES_VISITANTE)
            OR
            (P.ID_VISITANTE = C.ID_CLUB AND P.GOLES_VISITANTE > P.GOLES_LOCAL)
        ) THEN 3
        WHEN P.ID_STATUS = 5 AND P.GOLES_LOCAL = P.GOLES_VISITANTE 
        THEN 1
        ELSE 0
    END)
     AS PUNTOS
FROM CLUBES C
LEFT JOIN PARTIDOS P 
    ON C.ID_CLUB IN (P.ID_LOCAL, P.ID_VISITANTE)
    AND P.ID_TORNEO = 
LEFT JOIN TORNEOS T 
    ON T.ID_TORNEO = P.ID_TORNEO
GROUP BY C.NOMBRE_CLUB
ORDER BY PUNTOS DESC, DIFERENCIA_GOLES DESC, GOLES_A_FAVOR DESC
	