INSERT INTO TIPOS_ACONTECIMIENTOS (ID_TIPO,DESCRIPCION_TIPO) VALUES
	 (1,N'GOL'),
	 (2,N'CAMBIO'),
	 (3,N'PENAL'),
	 (4,N'TARJETA AMARILLA'),
	 (5,N'TARJETA ROJA'),
	 (6,N'CORNER'),
	 (7,N'TIRO LIBRE');
