BEGIN TRAN TRAN_1 
	BEGIN TRY

	IF OBJECT_ID ('dbo.TORNEOS') IS NOT NULL 
		DROP TABLE dbo.TORNEOS
	CREATE TABLE TORNEOS
	(
		ID_TORNEO BIGINT NOT NULL,
		NOMBRE_TORNEO NVARCHAR(100) NULL,
		FECHA_INICIO DATE NOT NULL,
		FECHA_FIN DATE NOT NULL,
		STATUS SMALLINT NULL,
		CONSTRAINT PK_TORNEO PRIMARY KEY(ID_TORNEO)
	)

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_VISITANTE]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_STATUS_PARTIDO]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_LOCAL]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_ESTADIO_PARTIDO]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_CUARTO_ARBITRO]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_ARBITRO_CENTRAL]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_ARBITRO_ASISTENTE2]

	ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [FK_ARBITRO_ASISTENTE1]

	ALTER TABLE [dbo].[ACONTECIMIENTOS] DROP CONSTRAINT [FK_PARTIDO_ACONTECIMIENTO]

	--ALTER TABLE [dbo].[PARTIDOS] DROP CONSTRAINT [DF__PARTIDOS__ID_PAR__4CA06362]


	IF OBJECT_ID('dbo.PARTIDOS') IS NOT NULL
	DROP TABLE dbo.PARTIDOS

	CREATE TABLE [dbo].[PARTIDOS](
	[ID_PARTIDO] UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() NOT NULL,
	[ID_LOCAL] [tinyint] NOT NULL,
	[ID_VISITANTE] [tinyint] NOT NULL,
	[ID_ESTADIO] [smallint] NOT NULL,
	[ID_ARBITRO_CENTRAL] [bigint] NOT NULL,
	[ID_CUARTO_ARBITRO] [bigint] NULL,
	[ID_ARBITRO_ASISTENTE1] [bigint] NULL,
	[ID_ARBITRO_ASISTENTE2] [bigint] NULL,
	[FECHA] [datetime] NOT NULL,
	[ID_STATUS] [tinyint] NOT NULL,
	ID_TORNEO	BIGINT NOT NULL,
	CONSTRAINT FK_PARTIDO_TORNEO FOREIGN KEY(ID_TORNEO) REFERENCES TORNEOS(ID_TORNEO) ON DELETE NO ACTION, 
	 CONSTRAINT [PK_PARTIDO] PRIMARY KEY CLUSTERED 
	(
		[ID_PARTIDO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]



	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ARBITRO_ASISTENTE1] FOREIGN KEY([ID_ARBITRO_ASISTENTE1])
	REFERENCES [dbo].[ARBITROS] ([NUI_ARBITRO])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_ARBITRO_ASISTENTE1]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ARBITRO_ASISTENTE2] FOREIGN KEY([ID_ARBITRO_ASISTENTE2])
	REFERENCES [dbo].[ARBITROS] ([NUI_ARBITRO])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_ARBITRO_ASISTENTE2]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ARBITRO_CENTRAL] FOREIGN KEY([ID_ARBITRO_CENTRAL])
	REFERENCES [dbo].[ARBITROS] ([NUI_ARBITRO])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_ARBITRO_CENTRAL]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_CUARTO_ARBITRO] FOREIGN KEY([ID_CUARTO_ARBITRO])
	REFERENCES [dbo].[ARBITROS] ([NUI_ARBITRO])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_CUARTO_ARBITRO]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ESTADIO_PARTIDO] FOREIGN KEY([ID_ESTADIO])
	REFERENCES [dbo].[ESTADIOS] ([ID_ESTADIO])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_ESTADIO_PARTIDO]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_LOCAL] FOREIGN KEY([ID_LOCAL])
	REFERENCES [dbo].[CLUBES] ([ID_CLUB])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_LOCAL]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_STATUS_PARTIDO] FOREIGN KEY([ID_STATUS])
	REFERENCES [dbo].[STATUS] ([ID_STATUS])
	
	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_STATUS_PARTIDO]

	ALTER TABLE [dbo].[PARTIDOS]  WITH CHECK ADD  CONSTRAINT [FK_VISITANTE] FOREIGN KEY([ID_VISITANTE])
	REFERENCES [dbo].[CLUBES] ([ID_CLUB])

	ALTER TABLE [dbo].[PARTIDOS] CHECK CONSTRAINT [FK_VISITANTE]

	ALTER TABLE [dbo].[ACONTECIMIENTOS]  WITH NOCHECK ADD  CONSTRAINT [FK_PARTIDO_ACONTECIMIENTO] FOREIGN KEY([ID_PARTIDO])
	REFERENCES [dbo].[PARTIDOS] ([ID_PARTIDO])
		
	COMMIT TRAN TRAN_1; 
	PRINT 'PROCESO EJECUTADO CORRECTAMENTE'; 
	END TRY 
BEGIN CATCH 
SELECT 'LINEA ERROR - '+ CAST(ERROR_LINE() AS VARCHAR(5)) + ':' + ERROR_MESSAGE(); 
ROLLBACK TRAN TRAN_1; PRINT 'OCURRIO UN ERROR EN EL PROCESO'; 
END CATCH		